apiVersion : apps/v1
kind: Deployment
metadata:
  name: tutorialapp
  labels:
    app: tutorialapp 
spec:
  replicas: 1
  selector:
    matchLabels:
        app: tutorialapp
  template:
    metadata:
      labels:
        app: tutorialapp 
    spec:
      containers:
        - name: tutorialapp
          image: moanjum/tutorial
          ports:
          - containerPort: 80