on:
  push:
    branches: 
      - master
    paths:
      - .github/workflows/gitCheck.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: testAction
      
      - name: Login via Az module
        continue-on-error: true
        uses: azure/login@v1.1
        with:
         creds: ${{secrets.AZ_SPN_CREDS}}
          
      - name: Check resource compliance
        uses: ./
        with:
          scopes: |
            /subscriptions/c00d16c7-6c1f-4c03-9be1-6934a4c49682/resourceGroups/az-pac-dev/providers/Microsoft.Web/sites/azpactestwebapp
          bearer-token: 'awd'
          poll-timeout: '20'