on:
  push:
    branches: 
      - master
    paths:
      - .github/workflows/gitCheck.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: testAction
      
      - name: Login via Az module
        continue-on-error: true
        uses: azure/login@v1.1
        with:
         creds: ${{secrets.AZ_SPN_CREDS}}
      
      - name: Check out default repository
        uses: actions/checkout@v2
        with:
          path: workflow
          
      - name: Check resource compliance
        uses: ./
        with:
          scopes: |
            ./workflow/policyFolder/WebOverHTTPS/policy.json
          bearer-token: 'awdddd'
          poll-timeout: '20'