on:
  push:
    branches: 
      - master
    paths:
      - .github/workflows/gitCheck.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - run: |
          echo 'trying to get all notes form policy-sync'
          git ls-tree --name-only -r refs/notes/policy-sync
          echo 'tried man'