on:
  push:
    branches: 
      - master
    paths:
      - .github/workflows/gitCheck.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - run: |
        echo 'trying to get all notes form policy-sync'
        git notes --ref policy-sync show
        echo 'tried man'