on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      
    # Set the target AKS cluster.
    - uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.MOANJUMCLUSTER_KUBE_CONFIG }}

    - uses: tauhid621/k8s-deploy@users/moanjum/addingForceFlag
      with:
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          moanjum/tutorial